### ISSUE TITLE
Return result dict, not result value

### ISSUE THREAD

**Issue by mcproger** [best-doctor/Mario#20]
Right now, method `SomePipeline.run` returns the first value from the dict, which is the result of the last pipe. How about returning the full dict?

For example:

```python
class Pipeline(BasePipeline):
    def make_some():
        return {'test1': 100500, 'test2': 200500}
```

Now, when I call `Pipeline().run()` it returns only `100500`. But I want to get `{'test1': 100500, 'test2': 200500}`

**Comment by mcproger** [comment]
@Melevir

**Comment by Melevir** [comment]
Not sure.

This approach can lead to god-pipeline, that does everything with all items and returns all you need.

On the other side, current API can be too strict.

**Comment by mcproger** [comment]
> This approach can lead to god-pipeline, that does everything with all items and returns all you need.

True. Actually, I can fix my problem with nested dict, like

```python
return {'result': {'test1': 100500, 'test2': 200500}}
```

Unfortunately, it also can lead to god-pipeline. I will think what we can do to resolve it.
